module Raiha
  module TLS
    class Handshake
      class Extension
        EXTENSION_TYPE: Hash[Symbol, Integer]

        attr_accessor extension_type: Integer
        attr_accessor extension_data: String

        def serialize: -> String
        def self.deserialize_extensions: (String, type: :client_hello | :server_hello | :hello_retry_request | :encrypted_extensions | :certificate | :certificate_request | :new_session_ticket) -> Array[Extension]
      end
    end
  end
end
