module Raiha::Quic
  module Handshake
    class CryptoSetup
      attr_reader perspective: Symbol

      def initialize: (perspective: Symbol, connection_id: Protocol::ConnectionID, ?version: Integer) -> void
      def available?: (Symbol level) -> bool
      def handshake_complete?: -> bool
      def rederive_initial_keys: (connection_id: Protocol::ConnectionID) -> void
      def set_handshake_keys: (client_secret: String, server_secret: String, cipher_suite: Raiha::TLS::CipherSuite) -> void
      def set_application_keys: (client_secret: String, server_secret: String, cipher_suite: Raiha::TLS::CipherSuite) -> void
      def set_early_keys: (client_early_traffic_secret: String, cipher_suite: Raiha::TLS::CipherSuite) -> void
      def discard_early_keys: -> void
      def encrypt: (String plaintext, packet_number: Integer, aad: String, level: Symbol) -> String
      def decrypt: (String ciphertext, packet_number: Integer, aad: String, level: Symbol) -> String
      def header_protection_mask: (String sample, level: Symbol, ?direction: Symbol) -> String
      def queue_crypto_data: (String data, level: Symbol) -> void
      def get_crypto_data: (level: Symbol) -> String?
      def pop_crypto_frame: (level: Symbol) -> { offset: Integer, data: String }?
      def requeue_crypto_data: (offset: Integer, data: String, level: Symbol) -> void
      def restart_initial_crypto: -> void
      def discard_keys: (Symbol level) -> void
      def update_keys: -> void
      def one_rtt_key_phase: -> bool
      def decrypt_next_phase: (String ciphertext, packet_number: Integer, aad: String) -> String

      private def aead_for_level: (Symbol level) -> (InitialAEAD | UpdatableAEAD)?
    end
  end
end
