module Raiha::Quic
  module StatelessReset
    TOKEN_LENGTH: Integer
    MIN_PACKET_LENGTH: Integer

    def self.build: (String token, ?min_size: Integer) -> String
    def self.match_token?: (String datagram, Array[String] tokens) -> bool
    def self.derive_token: (String reset_key, Protocol::ConnectionID | String connection_id) -> String
  end
end
