module Raiha
  module Qlog
    FILE_SCHEMA_CONTAINED: String
    FILE_SCHEMA_SEQUENTIAL: String
    SERIALIZATION_JSON: String
    SERIALIZATION_JSON_SEQ: String
    QUIC_EVENT_SCHEMA: String
    EPOCH_DEFAULT: String

    class Writer
      QLOG_VERSION: String

      attr_reader reference_time: Time

      def initialize: (output: (IO | StringIO | String), ?title: String?, ?description: String?) -> void
      def start_trace: (vantage_point: Symbol, connection_id: String) -> void
      def log: (Event event) -> void
      def flush: -> void
      def self.to_file: (String path, ?title: String?) { (Writer) -> void } -> void
    end

    class StreamingWriter
      attr_reader reference_time: Time

      def initialize: (output: (IO | StringIO)) -> void
      def start_trace: (vantage_point: Symbol, connection_id: String) -> void
      def log: (Event event) -> void
      def flush: -> void

      private def write_header: -> void
    end
  end
end
