module Raiha
  module TLS
    class Alert
      attr_accessor level_num: Integer
      attr_accessor description_num: Integer

      DESCRIPTIONS: Hash[Integer, Symbol]

      def self.level_num_to_sym: (Integer level_num) -> Symbol
      def self.description_num_to_sym: (Integer description_num) -> Symbol
      def self.deserialize: (String data) -> Alert

      def initialize: (?level_num: Integer, ?description_num: Integer, ?level: Symbol, ?description: Symbol) -> void
      def serialize: -> String
      def warning?: -> bool
      def fatal?: -> bool
      def level: -> Symbol
      def description: -> Symbol
      def humanize: -> { level: Symbol, description: Symbol }
    end
  end
end
