module Raiha
  module TLS
    class CipherSuite
      CIPHER_SUITES: Array[{name: Symbol, value: String, supported: bool}]

      @name: Symbol
      @value: String
      @supported: bool

      attr_reader name: Symbol
      attr_reader value: String

      def self.deserialize: (String) -> CipherSuite
      def initialize: (Symbol) -> void
      def serialize: -> String
      def supported?: -> bool
      def hash_algorithm: -> String
      def aead_algorithm: -> String
    end
  end
end
