module Raiha
  module TLS
    class Client
      module State
        START: :START
        WAIT_SH: :WAIT_SH
        WAIT_EE: :WAIT_EE
        WAIT_CERT_CR: :WAIT_CERT_CR
        WAIT_CERT: :WAIT_CERT
        WAIT_CV: :WAIT_CV
        WAIT_FINISHED: :WAIT_FINISHED
        WAIT_SEND_FINISHED: :WAIT_SEND_FINISHED
        CONNECTED: :CONNECTED
      end

      @state: Symbol
      @buffer: Array[String]
      @supported_groups: Array[untyped]
      @transcript_hash: untyped
      @received: Array[Record::TLSPlaintext|Record::TLSCiphertext]

      attr_reader state: Symbol

      def initialize: -> void
      def build_client_hello: -> Array[String]
      def datagrams_to_send: -> Array[String]
      def receive: (String datagram) -> void
      def receive_server_hello: -> void
      private def transition_state: (Symbol state) -> void
    end
  end
end
