module Raiha
  module TLS
    class Handshake
      HANDSHAKE_TYPE: Hash[Symbol, Integer]

      attr_accessor handshake_type: Integer
      attr_accessor length: Integer
      attr_accessor message: Message

      def serialize: -> String
      def self.deserialize: (String data) -> Handshake?
    end
  end
end
