module Raiha
  module TLS
    class KeySchedule
      attr_accessor pkey: (OpenSSL::PKey::PKey | OpenSSL::PKey::EC)
      attr_accessor group: String
      attr_accessor public_key: String
      attr_reader shared_secret: String
      attr_reader client_handshake_traffic_secret: String
      attr_reader server_handshake_traffic_secret: String
      attr_reader client_application_traffic_secret: Array[String]
      attr_reader server_application_traffic_secret: Array[String]

      @hash_algorithm: String
      @aead_algorithm: String
      @client_early_traffic_secret: String
      @early_exporter_secret: String
      @client_handshake_traffic_secret: String
      @server_handshake_traffic_secret: String
      @client_application_traffic_secret: Array[String]
      @server_application_traffic_secret: Array[String]
      @exporter_secret: String
      @resumption_secret: String
      @ikm: { early_secret: String, handshake_secret: String, main_secret: String }
      @salt: { main_secret: String }
      @server_handshake_write_key: String
      @server_handshake_write_iv: String
      @client_application_write_key: String
      @client_application_write_iv: String
      @server_application_write_key: String
      @server_application_write_iv: String

      def initialize: (mode: :client|:server) -> void
      def compute_shared_secret: -> void
      def cipher_suite=: (CipherSuite cipher_suite) -> void
      def derive_secret: (secret: :early_secret|:handshake_secret|:main_secret, label: String, transcript_hash: String) -> String
      def hkdf_label: (Integer length, String label, String context) -> String

      def transcript_hash: (Array[String] messages) -> String
      # def derive_binder_key: -> String
      def client_early_traffic_secret: (Raiha::TLS::Handshake client_hello) -> String
      def early_exporter_secret: (Raiha::TLS::Handshake client_hello) -> String
      def derive_client_handshake_traffic_secret: (String transcript_hash) -> String
      def derive_server_handshake_traffic_secret: (String transcript_hash) -> String
      def server_handshake_write_key: -> String
      def server_handshake_write_iv: -> String
      def derive_client_application_traffic_secret: (String transcript_hash) -> String
      def derive_server_application_traffic_secret: (String transcript_hash) -> String
      def exporter_secret: (Array[Raiha::TLS::Handshake] messages) -> String
      def resumption_secret: (Array[Raiha::TLS::Handshake] messages) -> String

      private def hkdf_expand: (prk: String, info: String, length: Integer) -> String
    end
  end
end
