module Raiha
  module TLS
    class Record
      CONTENT_TYPE: Hash[Symbol, Integer]
      LEGACY_RECORD_VERSION: String

      def self.deserialize: (String buf) -> Array[TLSPlaintext|TLSCiphertext]
      def self.unwrap_fragments: (String serialized_records) -> Array[{content_type: Integer, length: Integer, fragment: String}]

      class TLSPlaintext
        FRAGMENT_SIZE_LIMIT: Integer

        attr_accessor content_type: Integer
        attr_accessor length: Integer
        attr_accessor fragment: ChangeCipherSpec|Handshake

        def self.serialize: (Handshake content)-> Array[String]
      end

      class TLSCiphertext
        attr_reader content_type: Integer
        attr_accessor length: Integer
        attr_accessor encrypted_record: String
        attr_accessor tls_inner_plaintext: TLSInnerPlaintext|nil

      end

      class TLSInnerPlaintext
        # attr_accessor content: Handshake # TODO
        attr_accessor content: String
        attr_accessor content_type: Integer
        attr_accessor zeros: Integer

        def self.deserialize: (String data) -> TLSInnerPlaintext
      end
    end
  end
end

