module Raiha
  module TLS
    class SampleHttpsClient
      def self.start: (?host: String, ?port: Integer) -> void
      def initialize: (host: String, port: Integer) -> void
      def connect!: -> void
      def read: -> String?
      def close: -> void
      def send: (String data) -> Integer
    end
  end
end
