module Raiha
  module TLS
    class Server < Context
      module State
        START: :START
        RECVD_CH: :RECVD_CH
        NEGOTIATED: :NEGOTIATED
        WAIT_EOED: :WAIT_EOED
        WAIT_FLIGHT2: :WAIT_FLIGHT2
        WAIT_CERT: :WAIT_CERT
        WAIT_CV: :WAIT_CV
        WAIT_FINISHED: :WAIT_FINISHED
        CONNECTED: :CONNECTED
      end

      @state: Symbol

      attr_reader state: Symbol

      def initialize: -> void
      def datagrams_to_send: -> Array[String]
      def receive: (Array[String] datagrams) -> void
      private def transition_state: (State) -> void
    end
  end
end
