module Raiha
  module TLS
    class Server < Context
      module State
        START: :START
        RECVD_CH: :RECVD_CH
        NEGOTIATED: :NEGOTIATED
        WAIT_EOED: :WAIT_EOED
        WAIT_FLIGHT2: :WAIT_FLIGHT2
        WAIT_CERT: :WAIT_CERT
        WAIT_CV: :WAIT_CV
        WAIT_FINISHED: :WAIT_FINISHED
        CONNECTED: :CONNECTED
        ERROR_OCCURED: :ERROR_OCCURED
      end

      @state: Symbol
      @cipher_suite: CipherSuite?

      attr_reader state: Symbol

      def initialize: -> void
      def datagrams_to_send: -> Array[String]
      def receive: (String datagram) -> void
      def choose_cipher_suite: (Array[CipherSuite] cipher_suites) -> CipherSuite?
      private def transition_state: (Symbol state) -> void
    end
  end
end
