module Raiha
  module TLS
    class Server < Peer
      module State
        START: :START
        RECVD_CH: :RECVD_CH
        NEGOTIATED: :NEGOTIATED
        WAIT_EOED: :WAIT_EOED
        WAIT_FLIGHT2: :WAIT_FLIGHT2
        WAIT_CERT: :WAIT_CERT
        WAIT_CV: :WAIT_CV
        WAIT_FINISHED: :WAIT_FINISHED
        CONNECTED: :CONNECTED
        WAIT_CH_RETRY: :WAIT_CH_RETRY
        ERROR_OCCURED: :ERROR_OCCURED
      end

      @cipher_suite: CipherSuite?
      @config: Config
      @client_auth_required: bool
      @psk_mode: bool
      @selected_psk: { index: Integer, psk: String }?

      attr_reader client_hello: Handshake::ClientHello?
      attr_reader early_data_available: bool

      def initialize: (?config: Config) -> void
      def datagrams_to_send: -> Array[String]?
      def receive: (String datagram) -> void
      def receive_client_hello: -> void
      def choose_cipher_suite: -> CipherSuite?
      def choose_group: -> void
      def select_parameters: -> void
      def connected?: -> bool

      def build_new_session_ticket: (?application_data: String?) -> String
      def build_new_session_ticket_handshake: (?application_data: String?) -> Handshake
      def build_change_cipher_spec: -> Array[String]
      def build_hello_retry_request: -> Array[String]
      def build_error_alert: (Alert alert) -> Array[String]
      def build_server_hello: -> Array[String]
      def build_encrypted_extensions: -> String
      def build_certificate_request: -> String
      def build_certificate: -> String
      def build_certificate_verify: -> String
      def build_finished: -> String
      def receive_finished: -> void
      def verify_client_finished: (Handshake handshake) -> bool
      def response_flight_bytes: (Symbol level) -> String?

      private def receive_retry_client_hello: -> void
      private def check_psk: -> void
      private def check_early_data: -> void
      private def verify_psk_binder: (String psk, String binder, Integer identity_index) -> bool
      private def compute_binders_size: (Integer target_index) -> Integer
      private def check_key_share_or_retry: -> void
      private def transition_state: (Symbol state) -> void
      private def setup_key_schedule: -> void
      private def verify_finished: (Handshake finished) -> void
    end
  end
end
