module Raiha
  module TLS
    class SessionTicketStore
      @tickets: Hash[String, { ticket: String, ticket_nonce: String, psk: String, received_at: Time, lifetime: Integer, age_add: Integer, extensions: Array[untyped] }]

      def initialize: -> void
      def store: (String server_name, Handshake::NewSessionTicket ticket_message, String psk) -> void
      def get: (String server_name) -> ({ ticket: String, ticket_nonce: String, psk: String, received_at: Time, lifetime: Integer, age_add: Integer, extensions: Array[untyped] } | nil)
      def delete: (String server_name) -> void

      private def expired?: ({ received_at: Time, lifetime: Integer } entry) -> bool
    end
  end
end
