module Raiha
  module TLS
    class Handshake
      class Extension
        class CertificateAuthorities < AbstractExtension
          EXTENSION_TYPE_NUMBER: 47
        end
      end
    end
  end
end
