module Raiha
  module TLS
    class Handshake
      class Extension
        class ClientCertificateType < AbstractExtension
          EXTENSION_TYPE_NUMBER: 19
        end
      end
    end
  end
end
