module Raiha
  module TLS
    class Handshake
      class Extension
        class EarlyData < AbstractExtension
          EXTENSION_TYPE_NUMBER: 42

          attr_accessor max_early_data_size: Integer?
          attr_accessor context: Symbol?
        end
      end
    end
  end
end
