module Raiha
  module TLS
    class Handshake
      class Extension
        class PreSharedKey < AbstractExtension
          EXTENSION_TYPE_NUMBER: 41

          class PskIdentity
            attr_accessor identity: String
            attr_accessor obfuscated_ticket_age: Integer
            def initialize: (String identity, Integer obfuscated_ticket_age) -> void
          end

          attr_accessor identities: Array[PskIdentity]
          attr_accessor binders: Array[String]
          attr_accessor selected_identity: Integer?

          private def deserialize_offered_psks: (StringIO buf) -> void
          private def serialize_offered_psks: -> String
        end
      end
    end
  end
end
