module Raiha
  module TLS
    class Handshake
      class Extension
        class ServerCertificateType < AbstractExtension
          EXTENSION_TYPE_NUMBER: 20
        end
      end
    end
  end
end
