module Raiha
  module TLS
    class Handshake
      class Extension
        class SignatureAlgorithmsCert < AbstractExtension
          EXTENSION_TYPE_NUMBER: 50
        end
      end
    end
  end
end
