module Raiha
  module TLS
    class Handshake
      class Extension
        class SupportedVersions < AbstractExtension
          EXTENSION_TYPE_NUMBER: 43
          def self.generate_for_tls13: ->  SupportedVersions
        end
      end
    end
  end
end
