module Raiha
  module HTTP3
    class Client
      @control_stream: Raiha::Stream?
      @qpack_encoder_stream: Raiha::Stream?
      @qpack_decoder_stream: Raiha::Stream?

      def initialize: (connection: Raiha::Connection) -> void
      def setup_control_stream: (?settings: Hash[Integer, Integer]) -> Raiha::Stream
      def setup_qpack_streams: -> nil
      def receive_peer_control_stream: (Raiha::Stream stream) -> SettingsFrame?
      def send_request: (method: String, scheme: String, authority: String, path: String, ?headers: Array[[String, String]], ?body: String?) -> Raiha::Stream
      def receive_response: (Raiha::Stream stream) -> Response

      private def default_settings: -> Hash[Integer, Integer]
      private def open_unidirectional_with_type: (Integer type, ?extra_data: String?) -> Raiha::Stream
    end
  end
end
