module Raiha::Quic::Wire::Frames
  class CryptoFrame < Raiha::Quic::Wire::Frame
    attr_accessor offset: Integer
    attr_accessor data: String

    def self.parse: (Raiha::Quic::Wire::Buffer buffer) -> CryptoFrame
    def serialize: -> String
    def frame_type: -> Integer
  end
end
