module Raiha::Quic::Wire::Frames
  class PathResponseFrame < Raiha::Quic::Wire::Frame
    attr_accessor data: String

    def self.parse: (Raiha::Quic::Wire::Buffer buffer) -> PathResponseFrame
    def serialize: -> String
    def frame_type: -> Integer
  end
end
