module Raiha::Quic::Wire::Frames
  class StreamDataBlockedFrame < Raiha::Quic::Wire::Frame
    attr_accessor stream_id: Integer
    attr_accessor maximum_stream_data: Integer

    def self.parse: (Raiha::Quic::Wire::Buffer buffer) -> StreamDataBlockedFrame
    def serialize: -> String
    def frame_type: -> Integer
  end
end
