module Raiha::CryptoUtil
  def self?.hkdf_expand_label: (String secret, String label, String context, Integer length) -> String
  def self?.hkdf_expand: (String prk, String info, Integer length) -> String
end
