module Raiha
  module TLS
    class TLSError < Raiha::Error
    end

    class Context
      @state: untyped
    end

    class Client < Context
      module State
        START: Symbol
      end
    end

    class Server < Context
    end
  end
end
